---
version: 2
plan:
  project-key: NOD
  key: NOD
  name: Node-plan

stages:
- Checkout Code:
    manual: false
    final: false
    jobs:
    - Checkout Job
- Build Docker Image:
    manual: false
    final: false
    jobs:
    - Build Job
- Run Docker Container:
    manual: false
    final: false
    jobs:
    - Run Job

Checkout Job:
  key: JOB1
  tasks:
  - checkout: {}
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash
        echo "Code checked out successfully."
      description: Checkout code
  artifact-subscriptions: []

Build Job:
  key: JOB2
  tasks:
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash
        echo "Building Docker image..."

        # Build Docker image
        docker build -t node-app:latest .

        echo "Docker image built: node-app:latest"
      description: Build Docker Image
  artifact-subscriptions: []

Run Job:
  key: JOB3
  tasks:
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash
        echo "Running Docker container..."

        # Run container
        docker run -d -p 3000:3000 --name node-app node-app:latest

        echo "Container started on port 3000"
      description: Run Docker Container
  artifact-subscriptions: []

repositories:
- Nodeapp:
    scope: global

triggers:
- github-trigger

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications: []
labels: []

dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []

other:
  concurrent-build-plugin:
    number-of-concurrent-builds: system-default
    execution-strategy: block-triggering
---
version: 2
plan:
  key: NOD-NOD
plan-permissions:
- users:
  - root
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
  - view-configuration
  - create-plan-branch
- roles:
  - logged-in
  - anonymous
  permissions:
  - view
...
